<?php
class StudenT extends User
{
    private $course;

    public function getCourse()
    {
        return $this->course;
    }
    public function setCourse($course)
    {
        $this->course = $course.' курс';
    }
    public function addOneYear()
    {
        $this->age++;
    }
    public function setName($name)
    {
        if ((mb_strlen($name) <= 10)) {

            parent::setName($name); // TODO: Change the autogenerated stub
        }
    }
}
